apiVersion: v1
kind: Secret
metadata:
  name: agents-secrets
  namespace: atlas-ai
type: Opaque
stringData:
  JWT_SECRET_KEY: "C-J31gshBZl_iuAV42TfNNcPv2O3LJDMrjPqZyoHLKA"
  ENCRYPTION_KEY: "4AbUUOv0NKJjznNeMu-PKGEmh-KJvez1onwYU0vzNUo="
  POSTGRES_PASSWORD: "agents-prod-k8s-2024"
